import { type AppType } from "next/app";
import { api } from "@/utils/api";
import "@/styles/globals.css";

import { useEffect, useRef } from "react";
import { Noto_Sans_JP } from "next/font/google";
import Head from "next/head";
import { MainScene } from "@/gl/parts/MainScene";

const font = Noto_Sans_JP({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--noto-font",
});

const MyApp: AppType = ({ Component, pageProps }) => {
  const three = useRef<MainScene>();
  const canvas = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    if (three.current) return;
    if (!canvas.current) return;

    three.current = new MainScene({
      el: canvas.current,
    });
  }, []);

  return (
    <main className={font.variable}>
      <Head>
        <title>Reactive Carousel</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-screen w-full items-center justify-center">
        <Component {...pageProps} />
      </div>
    </main>
  );
};

export default api.withTRPC(MyApp);
